# -*- coding: utf-8 -*-
"""TUBES KECERDASAN BUATAN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-wd6Rmu8u0Z8M3-DdY6VOlfTCL5Asp3

# Sistem Pendukung Keputusan Pemilihan Bengkel Terbaik
## Metode Fuzzy Logic Mamdani

Deskripsi Proyek:
Proyek ini merupakan implementasi Sistem Fuzzy Logic menggunakan metode Mamdani untuk membantu menentukan 5 bengkel terbaik berdasarkan beberapa kriteria, yaitu kualitas servis dan harga. Sistem fuzzy digunakan karena mampu menangani nilai yang bersifat tidak pasti dan subjektif, sehingga keputusan yang dihasilkan lebih fleksibel dan mendekati cara berpikir manusia.

Pada proyek ini, setiap data bengkel akan melalui tahapan fuzzifikasi, inferensi, dan defuzzifikasi untuk menghasilkan skor kelayakan. Proses fuzzifikasi dilakukan dengan mengubah nilai numerik menjadi derajat keanggotaan berdasarkan fungsi keanggotaan segitiga. Selanjutnya, aturan inferensi fuzzy Mamdani diterapkan untuk menentukan tingkat kelayakan bengkel. Hasil inferensi kemudian diubah menjadi nilai tegas menggunakan metode Centroid (Center of Gravity).

Seluruh proses fuzzy diimplementasikan secara manual tanpa menggunakan library fuzzy, sesuai dengan ketentuan tugas. Output akhir dari program ini adalah daftar 5 bengkel terbaik yang diurutkan berdasarkan skor kelayakan tertinggi dan disimpan ke dalam file sebagai hasil akhir sistem.

## Import Library
"""

import csv

"""## Load Dataset

### Membaca Dataset Bengkel

Dataset berisi 50 bengkel dengan atribut:
- id_bengkel
- kualitas_servis (0–100)
- harga (rupiah)

"""

def baca_data(filename):
    data = []
    with open(filename, 'r') as file:
        reader = csv.DictReader(file, delimiter=';') # Specify semicolon as delimiter
        # Print the actual headers for debugging
        print(f"Actual CSV Headers: {reader.fieldnames}")
        for row in reader:
            data.append({
                'id': row['id_bengkel'],
                'kualitas': float(row['kualitas_servis']),
                'harga': float(row['harga']) / 100000  # NORMALISASI
            })
    return data

data_bengkel = baca_data('/content/dataset_bengkel.csv')
data_bengkel

"""##Fungsi Keanggotaan segitiga
Mendefinisikan fungsi keanggotaan segitiga yang digunakan sebagai dasar perhitungan derajat keanggotaan pada proses fuzzifikasi.
"""

def segitiga(x, a, b, c):
    if x <= a or x >= c:
        return 0
    elif a < x < b:
        return (x - a) / (b - a)
    elif b <= x < c:
        return (c - x) / (c - b)

"""## FUZZIFIKASI KUALITAS SERVIS
Melakukan proses fuzzifikasi pada atribut kualitas servis dengan membagi nilai input ke dalam himpunan linguistik buruk, cukup, dan baik.
"""

def fuzzifikasi_kualitas(x):
    return {
        'buruk': segitiga(x, 0, 0, 60),
        'cukup': segitiga(x, 50, 70, 90),
        'baik': segitiga(x, 80, 100, 100)
    }

fuzzifikasi_kualitas(85)

"""## FUZZIFIKASI HARGA
Cell ini melakukan proses fuzzifikasi pada atribut harga dengan membagi nilai input ke dalam himpunan linguistik murah, sedang, dan mahal.
"""

def fuzzifikasi_harga(x):
    return {
        'murah': segitiga(x, 0, 0, 5),
        'sedang': segitiga(x, 4, 6, 8),
        'mahal': segitiga(x, 7, 10, 10)
    }

fuzzifikasi_harga(4)

"""## INFERENSI (RULE MAMDANI)
Menerapkan aturan inferensi fuzzy menggunakan metode Mamdani dengan operator AND (minimum) dan OR (maximum) untuk menentukan tingkat kelayakan bengkel.
"""

def inferensi(kualitas, harga):
    tidak_layak = max(
        kualitas['buruk'],
        harga['mahal']
    )

    layak = min(
        kualitas['cukup'],
        harga['sedang']
    )

    sangat_layak = min(
        kualitas['baik'],
        harga['murah']
    )

    return {
        'tidak_layak': tidak_layak,
        'layak': layak,
        'sangat_layak': sangat_layak
    }

"""## DEFUZZIFIKASI (CENTROID)
Metode: Centroid (COG) diskret

Melakukan proses defuzzifikasi menggunakan metode Centroid untuk mengubah hasil inferensi fuzzy menjadi satu nilai tegas berupa skor kelayakan.
"""

def defuzzifikasi(output):
    pembilang = (
        output['tidak_layak'] * 30 +
        output['layak'] * 60 +
        output['sangat_layak'] * 90
    )

    penyebut = (
        output['tidak_layak'] +
        output['layak'] +
        output['sangat_layak']
    )

    if penyebut == 0:
        return 0

    return pembilang / penyebut

"""## PROSES SEMUA DATA BENGKEL

Menjalankan seluruh tahapan fuzzy (fuzzifikasi, inferensi, dan defuzzifikasi) pada setiap data bengkel untuk mendapatkan skor kelayakan masing-masing bengkel.
"""

hasil = []

for b in data_bengkel:
    fk = fuzzifikasi_kualitas(b['kualitas'])
    fh = fuzzifikasi_harga(b['harga'])
    inf = inferensi(fk, fh)
    skor = defuzzifikasi(inf)

    hasil.append({
        'id': b['id'],
        'kualitas': b['kualitas'],
        'harga': b['harga'],
        'skor': skor
    })

hasil
hasil = []

for b in data_bengkel:
    fk = fuzzifikasi_kualitas(b['kualitas'])
    fh = fuzzifikasi_harga(b['harga'])
    inf = inferensi(fk, fh)
    skor = defuzzifikasi(inf)

    hasil.append({
        'id': b['id'],
        'kualitas': b['kualitas'],
        'harga': b['harga'],
        'skor': skor
    })

hasil

"""##Penentuan Kategori Rekomendasi Bengkel

"""

def label_rekomendasi(skor):
    if skor >= 80:
        return "Sangat Direkomendasikan"
    elif skor >= 60:
        return "Direkomendasikan"
    else:
        return "Tidak Direkomendasikan"

"""##MENGRUTKAN & AMBIL 5 TERBAIK

Mengurutkan bengkel berdasarkan skor kelayakan tertinggi dan mengambil 5 bengkel terbaik sebagai hasil akhir sistem fuzzy.
"""

print("5 Bengkel Terbaik")
print("=" * 90)
print(f"{'No':<5}{'ID Bengkel':<12}{'Kualitas':<12}{'Harga':<10}{'Skor':<10}{'Rekomendasi'}")
print("=" * 90)

for i, b in enumerate(top5, start=1):
    print(
        f"{i:<5}"
        f"{b['id']:<12}"
        f"{b['kualitas']:<12.1f}"
        f"{b['harga']:<10.1f}"
        f"{b['skor']:<10.2f}"
        f"{label_rekomendasi(b['skor'])}"
    )

"""##SIMPAN KE FILE"""

with open('hasil.txt', 'w') as f:
    for b in top5:
        f.write(
            f"{b['id']} | kualitas: {b['kualitas']} | harga: {b['harga']} | skor: {b['skor']:.2f}\n"
        )